### ISSUE TITLE
Stopped working on Windows 10 build 1809

### ISSUE THREAD

**Issue by ujLion** [vadash/1000hz#3]
It was working fine on Windows 10 build 1803 but after upgrading to build 1809 - it has ceased to work.
No change in mouse rate is detected by Mouse rate checker even after the Setup.exe > Install service > restart step.

**Comment by vadash** [comment]
check original thread https://www.overclock.net/forum/375-mice/1589644-usb-mouse-hard-overclocking-2000-hz.html
